---
abstract: 'Perl modules for Current Cost energy monitors'
author:
  - 'Mark Hindess <soft-cpan@temporalanomaly.com>'
build_requires:
  IO::Pipe: '0'
  Test::More: '0'
  Test::Requires: '0'
  Test::SharedFork: '0'
  Test::Warn: '0'
  lib: '0'
configure_requires:
  ExtUtils::MakeMaker: '6.30'
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.019, CPAN::Meta::Converter version 2.141520'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Device-CurrentCost
requires:
  Carp: '0'
  Device::SerialPort: '0'
  Fcntl: '0'
  Getopt::Long: '0'
  IO::Handle: '0'
  IO::Select: '0'
  List::Util: '0'
  Pod::Usage: '0'
  Symbol: '0'
  Time::HiRes: '0'
  constant: '0'
  strict: '0'
  warnings: '0'
resources:
  bugtracker: https://github.com/beanz/device-current-cost-perl/issues
  repository: git://github.com/beanz/device-current-cost-perl.git
version: '1.142000'
